.TH YED-MAN 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
man \- Open and view man pages in the special buffer *man-page.
.SH CONFIGURATION
None
.SH COMMANDS
.SS man <arguments>
Run "man <arguments>" as a subprocess and collect the output in the special buffer *man-page.
.SS man-word
Equivalent to running "man word-under-cursor".
.SH BUFFERS
*man-page
.SH NOTES
None
.SH VERSION
0.0.1
.SH KEYWORDS
man, manual, page, cursor, help
