.TH YED-CALC 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
calc \- An interactive calculator in the special buffer *calc.
.SH CONFIGURATION
None
.SH COMMANDS
.SS calc
Focus the *calc buffer.
.SH BUFFERS
*calc
.SH NOTES
.P
Each expression typed into the calculator is added to the history list and can be reused by its ans_* name.
Variables can be set by typing an expression of the form "name = expression".
.SH VERSION
0.0.1
.SH KEYWORDS
calc, calculator, math, expression, bc
