.TH YED-LANG-SYNTAX-GLSL 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
lang/syntax/glsl \- Syntax highlighting for the GLSL filetype.
.SH CONFIGURATION
None
.SH COMMANDS
None
.SH BUFFERS
None
.SH NOTES
None
.SH VERSION
0.0.1
.SH KEYWORDS
lang, language, filetype, file, syntax, highlight, opengl, glsl, GLSL, shader
