.TH YED-LANG-SYNTAX-YEDRC 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
lang/syntax/yedrc \- Syntax highlighting for the yedrc filetype.
.SH CONFIGURATION
None
.SH COMMANDS
None
.SH BUFFERS
None
.SH NOTES
None
.SH VERSION
0.0.1
.SH KEYWORDS
lang, language, filetype, file, syntax, highlight, yedrc
