.TH YED-LANG-SYNTAX-LATEX 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
lang/syntax/latex \- Syntax highlighting for the LaTeX filetype.
.SH CONFIGURATION
None
.SH COMMANDS
None
.SH BUFFERS
None
.SH NOTES
None
.SH VERSION
0.0.1
.SH KEYWORDS
lang, language, filetype, file, syntax, highlight, tex, Tex, latex, LaTeX
