.TH YED-JUMP_STACK 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
jump_stack \- Adds buffer locations to a stack so that they can be jumped back through later.
.SH CONFIGURATION
None
.SH COMMANDS
.SS jump-stack-push
Push the current cursor location to the jump stack.
.SS jump-stack-pop
Pop the top location from the stack and jump to it.
.SH BUFFERS
None
.SH NOTES
None
.SH VERSION
0.0.1
.SH KEYWORDS
jump, cursor, location, stack, line, remember
