#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

export LD_LIBRARY_PATH="$DIR:$LD_LIBRARY_PATH"
if [ "$(uname)" == "Darwin" ]; then
    export DYLD_LIBRARY_PATH="$DIR:$DYLD_LIBRARY_PATH"
fi

$DIR/_yed -i ${DIR}/plugins $@
