.TH YED-CURSOR_WORD_HL 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
cursor_word_hl \- Highlight occurences of the word under the cursor.
.SH CONFIGURATION
.SS cursor-word-hl-idle-threshold-ms <ms>
The number of milliseconds the cursor can be idle before the word under the cursor is highlighted.
.SH COMMANDS
None
.SH BUFFERS
None
.SH NOTES
Uses the "associate" style component.
.SH VERSION
0.0.1
.SH KEYWORDS
color, highlight, word, cursor, occurence
