.TH YED-LINE_NUMBERS 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
line_numbers \- Show line numbers in the left frame gutter.
.SH CONFIGURATION
None
.SH COMMANDS
None
.SH COMMANDS
None
.SH NOTES
Uses the "code_comment" style component to highlight numbers.
.SH VERSION
0.0.1
.SH KEYWORDS
frame, gutter, line, number, numbers
