.TH YED-LANG-CPP 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
lang/cpp \- Filetype for C++.
.SH CONFIGURATION
None
.SH COMMANDS
None
.SH BUFFERS
None
.SH NOTES
The filetype is called "C++".
Matches file extensions .cpp, .cxx, .hpp, .hxx, and .h.
If the extension is .h, a quick scan of the buffer see if it "looks like" C++ before setting the filetype to C++.
.SH VERSION
0.0.1
.SH KEYWORDS
lang, language, filetype, file, type, c++, c++, cpp, C++, cxx, CXX
