.TH YED-LANG-YEDRC 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
lang/yedrc \- Filetype for yedrc.
.SH CONFIGURATION
None
.SH COMMANDS
None
.SH BUFFERS
None
.SH NOTES
The filetype is called "yedrc".
Matches file extension .yedrc.
.SH VERSION
0.0.1
.SH KEYWORDS
lang, language, filetype, file, type, yedrc
