.TH YED-LANG-CONF 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
lang/conf \- Filetype for basic config files.
.SH CONFIGURATION
None
.SH COMMANDS
None
.SH BUFFERS
None
.SH NOTES
The filetype is called "Config".
Matches file extensions .conf and .config.
.SH VERSION
0.0.1
.SH KEYWORDS
lang, language, filetype, file, type, conf, config
