.TH YED-LANG-SYNTAX-PYTHON 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
lang/syntax/python \- Syntax highlighting for the Python filetype.
.SH CONFIGURATION
None
.SH COMMANDS
None
.SH BUFFERS
None
.SH NOTES
None
.SH VERSION
0.0.1
.SH KEYWORDS
lang, language, filetype, file, syntax, highlight, python, Python
