.TH YED-STYLE-FIRST 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
styles/first \- Two truecolor styles called first-dark and first-light. The first styles made for yed!
.SH CONFIGURATION
None
.SH COMMANDS
None
.SH BUFFERS
None
.SH NOTES
None
.SH VERSION
0.0.1
.SH KEYWORDS
style, color, theme
