.TH YED-SCROLL_BUFFER 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
scroll_buffer \- Move the buffer up/down lines while keeping the cursor in place.
.SH CONFIGURATION
None
.SH COMMANDS
.SS scroll-buffer <int>
Scroll the buffer some number of lines. If the argument is negative, the buffer is scrolled up. Positive down.
.SH BUFFERS
None
.SH NOTES
The cursor must always be in frame, so if the desired scroll would take the cursor out of view in the frame, the cursor is moved as well.
.SH VERSION
0.0.1
.SH KEYWORDS
scroll, cursor, view, frame, buffer, cursor
