.TH YED-LANG-SYNTAX-JGRAPH 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
lang/syntax/jgraph \- Syntax highlighting for the Jgraph filetype.
.SH CONFIGURATION
None
.SH COMMANDS
None
.SH BUFFERS
None
.SH NOTES
None
.SH VERSION
0.0.1
.SH KEYWORDS
lang, language, filetype, file, syntax, highlight, jgraph, Jgraph, graph, plot, chart
