.TH YED-STYLE_PICKER 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
style_picker \- An interactive buffer *style-picker-list that allows you to test styles that you have loaded.
.SH CONFIGURATION
None
.SH COMMANDS
.SS style-picker
Focuses *style-picker-list.
Pressing ENTER on a style will activate the style.
Leaving the frame will revert back to the style activated before style-picker was run.
.SH NOTES
None
.SH VERSION
0.0.1
.SH KEYWORDS
style, picker, menu, color, colors, theme, preview
