.TH YED-COMMENT 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
comment \- Toggles commenting of lines of code.
.SH CONFIGURATION
.SS cpp-style-comments [ yes / no ]
If this variable is true, single line C++ style comments will be used.
.SH COMMANDS
.SS comment-toggle
Toggles the current line. If there is a selection, toggles every line in the selection.
.SH BUFFERS
None
.SH NOTES
Implemented filetypes are: C, C++, Config, Golang, Zig, Shell, bJou, Python, yedrc, LaTeX
.SH VERSION
0.0.1
.SH KEYWORDS
toggle, comment
