.TH YED-ALIGN 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
align \- Align all first occurences of a string in a set of lines.
.SH CONFIGURATION
None
.SH COMMANDS
.SS align <string>
Align all of the first occurences of <string> in the selected lines to the rightmost match in the set.
.SH NOTES
None
.SH VERSION
0.0.1
.SH KEYWORDS
text, align, column, format
