.TH YED-LANG-SYNTAX-CPP 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
lang/syntax/cpp \- Syntax highlighting for the C++ filetype.
.SH CONFIGURATION
None
.SH COMMANDS
None
.SH BUFFERS
None
.SH NOTES
None
.SH VERSION
0.0.1
.SH KEYWORDS
lang, language, filetype, file, syntax, highlight, cpp, Cpp, c++, C++
