.TH YED-LANG-SYNTAX-SH 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
lang/syntax/sh \- Syntax highlighting for the Shell filetype.
.SH CONFIGURATION
None
.SH COMMANDS
None
.SH BUFFERS
None
.SH NOTES
None
.SH VERSION
0.0.1
.SH KEYWORDS
lang, language, filetype, file, syntax, highlight, sh, shell, Shell, bash, BASH, zsh
