.TH YED-LANG-LATEX 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
lang/latex \- Filetype for LaTeX.
.SH CONFIGURATION
None
.SH COMMANDS
None
.SH BUFFERS
None
.SH NOTES
The filetype is called "LaTeX".
Matches file extensions .tex and .cls.
.SH VERSION
0.0.1
.SH KEYWORDS
lang, language, filetype, file, type, tex, Tex, latex, LaTeX
