.TH YED-STYLE_USE_TERM_BG 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
style_use_term_bg \- Load/change styles to use the background color specified in your terminal. Useful for semi-transparent terminal backgrounds.
.SH CONFIGURATION
None
.SH COMMANDS
.SS style-use-term-bg
Change the current style to use the terminal background color.
.SS style-term-bg <style>
Activate <style>, but change it to use the terminal background color.
.SH BUFFERS
None
.SH NOTES
None
.SH VERSION
0.0.1
.SH KEYWORDS
style, terminal, color, background, transparent, alpha, opacity
