.TH YED-INDENT_C 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
indent_c \- Automatic indentation based on C-style languages.
.SH CONFIGURATION
None
.SH COMMANDS
.SS indent
Move the selected line(s) to the right one indentation level.
.SS unindent
Move the selected line(s) to the left one indentation level.
.SH BUFFERS
None
.SH NOTES
Uses the variable tab-width.

indent_c automatically increases and decreases the indentation level based on curly braces.
.SH VERSION
0.0.1
.SH KEYWORDS
indent, dedent, unindent, indentation
