.TH YED-LANG-MAKE 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
lang/make \- Filetype for Makefiles.
.SH CONFIGURATION
None
.SH COMMANDS
None
.SH BUFFERS
None
.SH NOTES
The filetype is called "Makefile".
Matches buffer names Makefile, makefile, GNUMakefile, Makefile.*, makefile.*.
.SH VERSION
0.0.1
.SH KEYWORDS
lang, language, filetype, file, type, make, makefile, Makefile
