.TH YED-HOOK 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
hook \- Run commands on editor events.
.SH CONFIGURATION
None
.SH COMMANDS
.SS hook [options] <event> <command>
Run <command> when <event> fires.
.SS hook-list-options
Print the available options to *log.
.SS hook-list-events
Print the available events to the command line.
.SH BUFFERS
None
.SH NOTES
This plugin is just a proof of concept at this point, but should be developed out more eventually.
.SH VERSION
0.0.1
.SH KEYWORDS
when, event, hook, pre, post, command, callback, handler
